neuromore/studio

src/Studio/Config.h, src/Studio/CrashReporter.cpp
Fixes https://github.com/neuromore/studio/issues/12
=> Fix, but also disable crashreporter in PRODUCTION_BUILD

src/Studio/Resources/NMStudio.rc
Was still set to 1.0.0 yet is 1.4.2
=> Set correct Studio Version in NMStudio.rc

src/Studio/Plugins/BackendFileSystem/CreateFileWindow.cpp
enable create statemachine and experience for community users
=> remove old hack

src/Studio/MainWindow.cpp
The Engine Status Plugin (with its useful performance feedback) will be also available in PRODUCTION_BUILD
=> Enable EngineStatus Plugin in Production Builds

src/Engine/User.h, src/QtBase/Backend/UsersCreateRequest.cpp, src/QtBase/Backend/UsersCreateRequest.h, src/QtBase/Backend/UsersGetResponse.cpp, src/Studio/Windows/CreateUserWindow.cpp, src/Studio/Windows/CreateUserWindow.h, src/Studio/Windows/SelectUserWindow.cpp
* Adds a birthday field to the internal user model
* Parses it from the JSON backend response
* Uses it instead of the Email field in the User Selection Table
* Adds birthday input to create user window
* Adds birthday value to create user backend request
=> Birthday in User Model, User Selection/Create

build/make/Makefile.common, build/vs/Studio.cmd, build/vs/Studio.vcxproj, build/vs/Studio.vcxproj.filters, src/Engine/Graph/ChannelSelectorNode.cpp, src/Studio/MainWindow.cpp, src/Studio/MainWindow.h, src/Studio/Windows/ExperienceWizardWindow.cpp, src/Studio/Windows/ExperienceWizardWindow.h, src/Studio/Windows/SelectUserWindow.cpp, src/Studio/Windows/SelectUserWindow.h
This adds a new feature/window called ExperienceWizard to neuromore Studio.
It allows to quickly create a customized experience for a selected user by:
a) Selecting a classifier
b) Selecting a state machine
c) Specifying a name for the experience
d) Configuring "quick config" nodes in the classifier
So far only supports 'channels' attribute of ChannelSelector node in (d).
But can be extended to support any kind of configuration for any kind of node.
Screenshot:
=> Experience Wizard

src/Studio/VisualizationManager.cpp, src/Studio/VisualizationManager.h
Allows new folder relation:
```
./Studio.exe
./Visualizations/*
```
On top of old:
```
./Studio.exe
./../Visualizations/*
```
=> find visualizations also in subfolder of exe

README.md
=> Fix cloud account registration link

src/Studio/MainWindow.cpp
Test:
Drag a window to another one, release the mouse = > Make sure it's added as new tab
Drag from the tab title to outside of the tabbed window area => Make sure the window is separated.
=> Added support for tabbed windows.

README.md, src/Studio/Plugins/Graph/GraphWidget.cpp, src/Studio/Plugins/Graph/GraphWidget.h
-[x] Restructure README (put prerequisites above building)
-[x] Make graph error messages more specific
=> Readme restructuring & Graph Error Messages

.github/workflows/build-win.yml
=> Update Windows CI (for new Cert)

.github/workflows/build-linux.yml
Remove some non required packages causing errors on upgrade.
=> Fix Ubuntu 22.04 in Github CI

src/Engine/Devices/OpenBCI/OpenBCIDevices.cpp, src/Engine/Devices/OpenBCI/OpenBCIDevices.h, src/Studio/Devices/OpenBCI/OpenBCIDriver.cpp, src/Studio/Devices/OpenBCI/OpenBCIDriver.h, src/Studio/Devices/OpenBCI/OpenBCISerialHandler.cpp, src/Studio/Widgets/ImpedanceTestWidget.cpp
Implements simple Impedance Testing for OpenBCI adapted from OpenBCI GUI.
=> OpenBCI Impedance Testing

src/Studio/Widgets/ImpedanceTestWidget.cpp, src/Studio/Widgets/ImpedanceTestWidget.h
Impedance Test
* Replaces single threshold value selection by selection of a threshold profile that includes multiple thresholds
* Now uses yellow and orange as intermediate colors between green and red
=> Impedance Threshold Profiles

src/QtBase/Networking/WebsocketServer.cpp, src/QtBase/Networking/WebsocketServer.h, src/Studio/Config.h, src/Studio/MainWindow.cpp, src/Studio/MainWindow.h
* Changes default websocket listen port from `1234` to `4547`
* Adds configuration setting for changing it to `Settings -> Network` (and according `.cfg` file)(Restart required!)
=> Add websocket port to settings and default to 4547

deps/build/make/platforms/detect-host.mk
Fixes building on ARM64 - specifically macOS. Linux/Win untested.
=> Improve ARCH detection in detect-host.mk

src/Studio/MainWindow.cpp
Removes some limitations in production builds:
* Allow user to properly switch cloud backend
=> Cleanup PRODUCTION_BUILD macro usage

.github/workflows/build-win.yml, deps/build/make/platforms/dist.mk
* Optimizes filename outputs of `make dist`
* Removes `.appx` files from Windows Github CI artifacts
=> Small Tweaks

src/Engine/BciDevice.h, src/Engine/Devices/OpenBCI/OpenBCIDevices.h, src/Studio/Plugins/Devices/BciDeviceWidget.cpp, src/Studio/Plugins/Devices/BciDeviceWidget.h, src/Studio/Plugins/Devices/DeviceWidget.cpp, src/Studio/Plugins/SessionControl/ClientInfoWidget.cpp, src/Studio/Plugins/SessionControl/PreSessionWidget.cpp, src/Studio/Plugins/SessionControl/SessionControlPlugin.cpp, src/Studio/Plugins/SessionControl/SessionInfoWidget.cpp, src/Studio/Plugins/SessionControl/StageControlWidget.cpp, src/Studio/Plugins/SessionControl/WhileSessionWidget.cpp, src/Studio/Widgets/ImpedanceTestWidget.cpp, src/Studio/Windows/ReportWindow.cpp
Layout Updates for Devices and Session Widget
=> Devices and Session Widget Tweaks

src/Studio/Plugins/BackendFileSystem/BackendFileSystemWidget.cpp, src/Studio/Plugins/BackendFileSystem/BackendFileSystemWidget.h
**Updated File Browser Widget**
* Context menu option `Save To HDD` renamed to `Download`
* Added recursive download of full folder
* Improved single file download
=> Full Folder Download

src/QtBase/Backend/FilesCreateResponse.cpp, src/QtBase/Backend/FilesCreateResponse.h, src/Studio/Plugins/BackendFileSystem/BackendFileSystemWidget.cpp, src/Studio/Plugins/BackendFileSystem/BackendFileSystemWidget.h
=> Folder Upload
