.gitattributes, build/vs/Engine.vcxproj, build/vs/Neuromore.sln, build/vs/QtBase.vcxproj, build/vs/Studio.vcxproj, deps/build/vs/crashrptprobe.vcxproj, deps/build/vs/crashsender.vcxproj, deps/build/vs/freetype.vcxproj, deps/build/vs/harfbuzz-ng.vcxproj, deps/build/vs/kissfft.vcxproj, deps/build/vs/libcrypto.vcxproj, deps/build/vs/libtheora.vcxproj, deps/build/vs/tinyobjloader.vcxproj, deps/build/vs/zlib.vcxproj
f1a2743 
The 'singleapplication' project in VS was not correctly set to require qt moc/rcc/uic first (fixes VS build error)
1bf5472
Disables more compiler warnings in VS when building dependencies.
6fddfb7
Removes some incorrect hard-coded paths from vs project files (fixes VS build error)
feb8f20
Windows Batch Files (CMD) must have CLRF after checkout (fixes VS build errors)
=> Fix VS build

README.md
Some basic info about the possible defines that can be used to customize the build (e.g. device support using proprietary sdk)
=> Add info about macros/defines to README.md

src/Engine/Config.h
This device does not require proprietary headers or libraries, so can be easily enabled in the build by default (like Muse).
Studio will try to start ./Mitsar/MitsarConnector.exe when you click the 'search device'  (the exe is from their SDK) which then streams to Studio using OSC.
Note:
Community Users seem to miss the rights to use the Mitsar, see rights check like:
https://github.com/neuromore/studio/blob/45e601aa8425b2bd91a7f650cf985d669a4ffd35/src/Studio/Devices/DriverInventory.cpp#L146
Unless two of them are uncommented or the community user rights are adjusted the Mitsar still won't be detected.
=> Enable Mitsar EEG device by default

deps/include/kissfft/kiss_fft.h
kissfft was upgraded from v130 to v131.
but used type was not switched from float (default) to double (as in old version and required).
this broke fft graph node and output view of its spectrum
=> Fix FFT, set kissfft from float to double

src/Engine/DeviceDriver.cpp, src/Engine/DeviceDriver.h, src/Studio/Devices/ABM/AbmDriver.cpp, src/Studio/Devices/ABM/AbmDriver.h, src/Studio/Devices/Audio/AudioDriver.cpp, src/Studio/Devices/Bluetooth/BluetoothDriver.cpp, src/Studio/Devices/Bluetooth/BluetoothDriver.h, src/Studio/Devices/BrainProducts/ActiChampDriver.cpp, src/Studio/Devices/Emotiv/EmotivDriver.cpp, src/Studio/Devices/EyeX/TobiiEyeXDriver.cpp, src/Studio/Devices/Mitsar/MitsarDriver.cpp, src/Studio/Devices/Mitsar/MitsarDriver.h, src/Studio/Devices/NeuroSky/NeuroSkyDriver.cpp, src/Studio/Devices/NeuroSky/NeuroSkyDriver.h, src/Studio/Devices/OpenBCI/OpenBCIDriver.cpp, src/Studio/Devices/Versus/VersusDriver.cpp
This improves handling of disabled devices a bit, specifically related to their Auto-Detection features.
So far devices always completely initialized (e.g. started their internal threads or their auto-scanning), even if they were disabled in the configuration, now they won't anymore.
For instance, enabling "Automatic Device Search" but keeping Bluetooth devices disabled, scanned in background for bluetooth devices and prompted you with a list every n seconds, but they were supposed to be disabled. This is fixed now.
Internally, drivers now also get constructed in disabled state and may get be enabled shortly after, according to the configuration, instead of being always initialized in enabled state and later (may be) disabled (at that moment everything was kicked up already).
=> Disabled Devices

src/Engine/Device.cpp
Device inactivity was inferred from mNumNewSamples of channels which can stay at 0 for some time because of drift-correction (e.g. larger thread blocks), even though the channel is actively receiving data and the device is fine. This caused devices (especially on larger app blocks) to get disconnected, especially when switching classifiers/experiences. Now device activity is inferred from isactive state of the channel, which is more safe.
=> Fix disconnect of devices that drift

src/Studio/Plugins/BackendFileSystem/BackendFileSystemWidget.cpp
* Fixes a small bug that caused the wrong filesystem tree item to be selected, when a drag'n'drop operation was started at the borders of a tree item and the mouse was directly and quickly moved up/down to the next element before the drag was really started.
* Filesystem widget now additionally supports dragging'n'dropping a file on another file with equal type and if user has update rights on destination file. This will copy the contents of the dragged file into the destination file and hence replace the old contents there (after confirmation popup).
=> CopyTo/Replace File by Drag'n'Drop (+small fix)

src/Studio/Plugins/Experience/ExperienceWidget.cpp, src/Studio/Plugins/Experience/ExperienceWidget.h, src/Studio/VideoPlayer.h
**Improves/Fixes Support for The Special Feedback Nodes**
These ones were refactored/fixed and will now work on all platforms:
* **Volume**: Controls volume of all active audio playbacks and the video playback
* **ScreenBrightness**: Controls alpha-blending of video/image playback with black (0.0=full black, 1.0=unchanged image)
This one still exists, but does work on Windows only:
* **MasterVolume**: Modifies active OS Audio-Device Volume.
This one has been removed:
* **LSD!**
All Windows GDI related code has been removed.
**Screenshot**
=> Refactor Special Feedbacks

src/Engine/Device.cpp, src/Engine/Device.h, src/Engine/DeviceManager.cpp, src/Engine/DeviceManager.h, src/Engine/Devices/Mitsar/MitsarDevices.cpp, src/Engine/Devices/Muse/MuseDevice.cpp
* Allows device classes to specify the OSC path pattern that they are interested in, instead of enforcing the old fixed pattern: `/{typename}/{int-id}/foo`
* Allows devices classes to provide the required integer device id from the OSC path whatever way they like, instead of enforcing it to be the second part in the route.
* Backwards compatible for Muse and Mitsar201 (devices already using OSC)
=> more flexible osc path pattern and id extract

src/Studio/MainWindow.cpp, src/Studio/Plugins/ExperienceSelection/ExperienceSelectionWidget.cpp, src/Studio/Plugins/SessionControl/PreSessionWidget.cpp, src/Studio/Plugins/SessionControl/SessionControlPlugin.cpp, src/Studio/Visualization.cpp, src/Studio/Visualization.h, src/Studio/VisualizationManager.h, src/Studio/Windows/VisualizationSelectWindow.cpp
This makes better use of QProcess class to improve tracking of the external visualization process.
**Summary**
* A running visualization is now closed if neuromore Studio is closed.
* Prevents starting a second visualization if one is running already
* Does not open the visualization selection popup if one is running already
* Closes a running visualization if Layout is switched to "Experience Selection" (and `STUDIO_SETTING_EasyWorkflow` is set for the current user)
=> Improve Visualization Process Interaction

src/Studio/Plugins/Experience/ExperienceWidget.cpp, src/Studio/Plugins/Experience/ExperienceWidget.h, src/Studio/Plugins/Graph/GraphWidget.cpp, src/Studio/Plugins/Graph/GraphWidget.h
When we stopped a session previously the experience window wasn't cleared. Hence the video/ audio would still keep playing and also the buttons/ text would still show.
This fix clears the experience window when the Stop button is pressed in the session control plugin.
=> Clear experience window when session is stopped

src/QtBase/FileManager.cpp, src/QtBase/FileManager.h
Issues:  
There were two problems in the flow both caused by the fact that  some actions of file cleanup/close are done after write backend some before that, and they were not synchronized:
- OpenClassifier closes the file,  in the reply handling setUndirty is called on the same file. 
- openGraph unloads the graph,  setUndirty is called in reply. 
Fixed by adding 'wait' mechanism to reply and put the file resource handling in appropriate places.
=> Fixed the crash on save.

.github/workflows/build-osx.yml, deps/build/make/platforms/dist.mk, deps/src/qt-platform-cocoa/qcocoahelpers.h, deps/src/qt-platform-cocoa/qcocoahelpers.mm
* Fixes ARM64 build on OSX by back-porting the according Qt changes from later 5.12.10
* Enables LIPO (univeral-binary) creation in `make dist`
* Runs OSX Github builds for X64 and ARM64 in parallel
=> Fix OSX ARM64

.github/workflows/build-osx.yml, .github/workflows/build-win.yml, build/make/Studio.mk, deps/build/make/platforms/dist.mk, dist/osx-10.15/Studio.Component.plist, dist/osx-10.15/Studio.Info.plist, dist/ubuntu-20.04/Studio.desktop, dist/ubuntu-22.04/Studio.desktop, dist/win-10/Studio.appxmanifest, dist/win-10/Studio.layout
**ALL**
* Changes the product name shown with icons, shortcuts (and in macOS Applications) from `Studio` to `neuromore Studio`
**WIN**
* Adds version number to filename of built packages, e.g. `Studio-1.6.4.appxbundle`
* Adds .PDB debug symbols to Github artifact `Binaries`
* Sets the short description in the package to `Your IDE for neuro-tech apps` (equal to macOS Store entry subtitle)
* Copies the binaries to the dist folder before doing anything with it (fixes issues with running repeated `make dist`)
**OSX**
* Adds version number to filename of built packages, e.g. `Studio-1.6.4.pkg`
* Renames unsigned macOS package from `NAME.pkg` to `NAME-unsigned.pkg` and uses without suffix for signed one.
* Cleans up the created dist folder files before creating new one (fixes issues with …
=> Change Display Name of App

build/vs/Engine.vcxproj, build/vs/EngineJNI.vcxproj, build/vs/EngineLIB.vcxproj, build/vs/QtBase.vcxproj, dist/win-10/Studio.appxmanifest, src/QtBase/Backend/WebDataCache.cpp, src/QtBase/LayoutManager.cpp, src/QtBase/Precompiled.h, src/QtBase/QtBaseManager.cpp
**Changes**
* Sets Visual Studio projects to `CXX17` (same as in Make)
* Replace Qt `mkpath()` calls (buggy in restricted Win10 App) with `std::filesystem::create_directories()` (fixes non-persistence issue on Win10 app install)
* Add some basic `DeviceCapability` settings for Serial and USB to `.appxmanifest` of Studio
=> Win10 Package Fixes | Tweaks

src/QtBase/Backend/NetworkAccessManager.cpp
* Changes old `test` backend to new `staging` backend
* Removes obsolete `swap` backend
* Makes `staging` and `localhost` backends also selectable in production builds.
=> neuromore staging back-end

.github/workflows/build-android.yml, .github/workflows/build-ios.yml, .github/workflows/build-linux.yml, .github/workflows/build-osx.yml, .github/workflows/build-win.yml
* Does not run Android CI pipeline on `macos-11` and `windows-2019` anymore
* Does not run iOS CI pipeline on `macos-11` anymore
* Does not create packages on `windows-2019` and `macos-11` anymore
* Updates `download-artifact` action to `v3` in macOS CI pipeline
* Checks out the repository once with GIT LFS in Linux CI and reuse it as artifact
=> Reduce Github Actions GIT LFS traffic

src/Engine/DSP/ResampleProcessor.cpp, src/Engine/Sensor.cpp
* Stop adding `0.0` if no last sample is available in `DoOutputLast()` in `ResampleProcessor.cpp`. Instead skip until a last sample is available (e.g. next tick).
* Also call `SetSampleRate()` for Input Port in `Sensor.cpp` as this is evaluated by `ResampleProcessor` and by default leads to DoOutputLast() if not set (and to resampling if not set identically)
* This fixes CSV values not correctly read (a single one was repeated many times)
=> Fix CSV Reader and fix some first zero case

src/Engine/Branding.h, src/Studio/Plugins/RawWaveform/RawWaveformPlugin.cpp, src/Studio/Plugins/Spectrogram2D/Spectrogram2DPlugin.cpp, src/Studio/Widgets/ChannelMultiSelectionWidget.cpp, src/Studio/Widgets/ChannelMultiSelectionWidget.h
Adds `SELECT_FIRST_TWO` as new `AutoSelectType` option and loads used value from branding constants.
=> Improve Channel Checkboxes Preselection

deps/src/qt-bluetooth/osx/osxbtconnectionmonitor.mm, deps/src/qt-bluetooth/osx/osxbtconnectionmonitor_p.h, deps/src/qt-bluetooth/qbluetoothlocaldevice_osx.mm
* Fixes crash on macOS when trying to connect to a HRM and Bluetooth permissions were already granted
* Ported from [official commit](https://github.com/qt/qtconnectivity/commit/bd1671ac91afafcd446e305cdb303838937eb332)
=> Fix Qt Bluetooth LE Crash on macOS

src/Engine/Branding.h, src/Studio/Widgets/ChannelMultiSelectionWidget.cpp, src/Studio/Widgets/ChannelMultiSelectionWidget.h, src/Studio/Widgets/HMultiCheckboxWidget.cpp, src/Studio/Widgets/HMultiCheckboxWidget.h
* RawEEG: Replaces infinitely growing `QHBoxLayout` for EEG Electrodes by `QGridLayout` with 8 columns
* RawEEG: Only select/show first 8 electrodes by default.
=> RawEEG: GridLayout for Electrode CheckBoxes

deps/include/qt/QtBluetooth/private/qlowenergycontroller_winrt_p.h, deps/src/qt-bluetooth/qbluetoothdevicediscoveryagent_winrt.cpp, deps/src/qt-bluetooth/qlowenergycontroller_winrt.cpp, src/Studio/Devices/Bluetooth/BluetoothDevice.cpp, src/Studio/Devices/Bluetooth/BluetoothDevice.h, src/Studio/Devices/Bluetooth/BluetoothDriver.cpp, src/Studio/Devices/Bluetooth/BluetoothDriver.h, src/Studio/Devices/BrainFlow/BrainFlowDriver.cpp
* Stop automatically enabling Brainflow driver whenever starting a device search even when it was disabled
* Backported some Qt fixes for BTLE on Windows
* [1](https://github.com/qt/qtconnectivity/commit/ed4f9f3c4354d4f65318832eadaf0cfc5c288404)
* [2](https://github.com/qt/qtconnectivity/commit/4ac755bb6e51891881b7477702be8ca917b60c8a)
* [3](https://codereview.qt-project.org/c/qt/qtconnectivity/+/392128)
* Make Auto-Detection work fine again with BTLE (at least on macOS)
* Filter for HRM and only show device popup if more than one HRM found
* Improve BTLE logging for HRM
* Check for BTLE support on Bluetooth device before doing anything BTLE like with it
=> Misc. Fixes

src/Engine/Core/EventHandler.h, src/Engine/Core/EventManager.h, src/Engine/EngineManager.cpp, src/Engine/Graph/Classifier.cpp, src/Engine/Graph/Classifier.h, src/Engine/Graph/Graph.cpp, src/Engine/Session.cpp, src/Engine/Session.h, src/Studio/MainWindow.cpp, src/Studio/MainWindow.h, src/Studio/Plugins/SessionControl/SessionControlPlugin.cpp, src/Studio/Plugins/SessionControl/SessionControlPlugin.h, src/Studio/Plugins/SessionControl/WhileSessionWidget.cpp, src/Studio/Plugins/SessionControl/WhileSessionWidget.h
* Adds a new classifier attribute `Init time (s)` (default: `0s`) to specify init phase until e.g. filters are stable
* Add classifier attributes to serialized and persisted JSON
* Session Start: 
* Starts a timer with specified classifier init time after resetting the Engine instead of starting session directly
* Keeps state-machine paused during initialization phase
* Shows a `Preparing` label in `Session Control` widget during new initialization phase
* Starts the session after time elapses
* Resets OutputNode and FileWriterNode once more to not persist samples from init phase
=> Decouple Engine Reset and Session Start

.github/workflows/build-win.yml
Uploads dedicated artifacts for portable ZIP and App installer
=> Split Win CI Artifacts

src/Engine/Core/TimermacOS.cpp, src/Engine/Core/TimermacOS.h
Use `clock_gettime_nsec_np(CLOCK_UPTIME_RAW)` instead of `mach_absolute_time()` to get a reliable nanosecond tick also on Apple Silicon
=> Fix Timinig on Apple Silicon

src/Studio/Plugins/Devices/BciDeviceWidget.cpp, src/Studio/Plugins/Devices/BciDeviceWidget.h, src/Studio/Plugins/Devices/DeviceWidget.cpp, src/Studio/Plugins/Devices/DeviceWidget.h
Shows impedance for up to eight channels in DeviceWidget (instead of just min/max/avg)
Looks like this:
=> Show All Impedances

src/Engine/BciDevice.cpp, src/Engine/BciDevice.h, src/Engine/Branding.h, src/Engine/Devices/OpenBCI/OpenBCIDevices.cpp, src/Engine/Devices/OpenBCI/OpenBCIDevices.h, src/Engine/Graph/ChannelSelectorNode.cpp, src/Engine/Graph/Classifier.h, src/Studio/Plugins/Devices/BciDeviceWidget.cpp, src/Studio/Plugins/Devices/DeviceWidget.cpp, src/Studio/Plugins/Devices/DeviceWidget.h, src/Studio/Plugins/SessionControl/SessionControlPlugin.cpp, src/Studio/Widgets/BatteryStatusWidget.cpp, src/Studio/Widgets/ImpedanceTestWidget.cpp, src/Studio/Widgets/ImpedanceTestWidget.h, src/Studio/Widgets/SignalQualityWidget.cpp
**FIXES**
* Sets default EEG channel buffer size to 60 seconds which is also the max. in the `Raw EEG` view settings.
* Fixes the Raw EEG plot sometimes not rendered to the left end of the timeline
**IMPROVEMENTS**
* Adds two new branding settings
* `HasColorCodesForChannels` activates a special coloring for channels in `Devices` view
* `HasMinimalDeviceInfo` limits info table in `Devices` view to most important stats
* Major refactoring of the `Devices` view and the impedance check in it, adding a table for up to 8 impedances, rearranging elements, supporting background impedance checks and more
Few other things...
=> Misc. Changes

src/Engine/Devices/OpenBCI/OpenBCIDevices.cpp, src/Engine/Devices/OpenBCI/OpenBCIDevices.h
**Tweaks for OpenBCI with Daisy**
* Changes channel names to numeric `1-16` numbers like on OpenBCI alone
* Sets large timeout like on OpenBCI alone (fixes device getting removed before fully connect)
=> Tweaks for OpenBCI with Daisy
